apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: certificate-rule-alerts
spec:
  groups:
  - name: certs-expiry-alerting-rules
    rules:
    - alert: PublicCertExpiredSoon
      annotations:
        summary: OSP Public Certificate has less than 6 months left to expire ({{ $value | humanizeDuration }})
        description: The openstack public certificate is about the expired in less than 6 months. Please renew
          the certificate according to https://docs.redhat.com/en/documentation/red_hat_openstack_platform/17.1/html/hardening_red_hat_openstack_platform/assembly_configuring-custom-ssl-tls-certificates#proc_creating-a-certificate-authority_configuring-custom-ssl-tls-certificates
      expr: |
        cert:time_to_expiration:sec{name="osp-public"} < 15552000
      labels:
        severity: warning
        resource_type: osp
    - alert: PublicCertExpiredSoon
      annotations:
        summary: OSP Public Certificate has less than 3 months left to expire ({{ $value | humanizeDuration }})
        description: The openstack public certificate is about the expired in less than 3 months. Please renew
          the certificate according to https://docs.redhat.com/en/documentation/red_hat_openstack_platform/17.1/html/hardening_red_hat_openstack_platform/assembly_configuring-custom-ssl-tls-certificates#proc_creating-a-certificate-authority_configuring-custom-ssl-tls-certificates
      expr: |
        cert:time_to_expiration:sec{name="osp-public"} < 7776000
      labels:
        severity: critical
        resource_type: osp
    - alert: RegistryMirrorCertExpiredSoon
      annotations:
        summary: Registry Mirror Certificate has less than 6 months left to expire ({{ $value | humanizeDuration }})
        description: The registry mirror certificate is about the expired in less than 6 months. Please renew
          the certificate.
      expr: |
        cert:time_to_expiration:sec{name="registry-mirror"} < 15552000
      labels:
        severity: warning
        resource_type: ocp
    - alert: RegistryMirrorCertExpiredSoon
      annotations:
        summary: Registry Mirror has less than 3 months left to expire ({{ $value | humanizeDuration }})
        description: The registry mirror certificate is about the expired in less than 3 months. Please renew
          the certificate.
      expr: |
        cert:time_to_expiration:sec{name="registry-mirror"} < 7776000
      labels:
        severity: critical
        resource_type: ocp
    - alert: ApiServerCertExpiredSoon
      annotations:
        summary: API Server Certificate has less than 6 months left to expire ({{ $value | humanizeDuration }})
        description: The API server certificate is about the expired in less than 6 months. Please renew
          the certificate according to https://docs.openshift.com/container-platform/4.16/security/certificates/api-server.html
      expr: |
        cert:time_to_expiration:sec{name="external-loadbalancer-serving-certkey"} < 15552000
      labels:
        severity: warning
        resource_type: ocp
    - alert: ApiServerCertExpiredSoon
      annotations:
        summary: API Server Certificate has less than 3 months left to expire ({{ $value | humanizeDuration }})
        description: The API server certificate is about the expired in less than 3 months. Please renew
          the certificate according to https://docs.openshift.com/container-platform/4.16/security/certificates/api-server.html
      expr: |
        cert:time_to_expiration:sec{name="external-loadbalancer-serving-certkey"} < 7776000
      labels:
        severity: critical
        resource_type: ocp
    - alert: IngressRouterExpiredSoon
      annotations:
        summary: Ingress Router Certificate has less than 6 months left to expire ({{ $value | humanizeDuration }})
        description: The Ingress Router certificate is about the expired in less than 6 months. Please renew
          the certificate according to https://docs.openshift.com/container-platform/4.16/security/certificates/replacing-default-ingress-certificate.html
      expr: |
        cert:time_to_expiration:sec{name="router-certs-default"} < 15552000
      labels:
        severity: warning
        resource_type: ocp
    - alert: IngressRouterExpiredSoon
      annotations:
        summary: Ingress Router Certificate has less than 3 months left to expire ({{ $value | humanizeDuration }})
        description: The Ingress Router certificate is about the expired in less than 3 months. Please renew
          the certificate according to https://docs.openshift.com/container-platform/4.16/security/certificates/replacing-default-ingress-certificate.html
      expr: |
        cert:time_to_expiration:sec{name="router-certs-default"} < 7776000
      labels:
        severity: critical
        resource_type: ocp





